# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54c417abc035a028e9295e816704c72d8f53388c13b31a1fc311e7e9753639e6bd9184dd665f689796f25e8be36b496ca0650ae25429fc5713bbcb130acd66b6

test:
  secret_key_base: a20d83dd19ab8c49e79aee7a4e1db92238e99056635ae157a05b4d774da1ae1a2f54bef477c255eaaaa2dda52b721470f5f69444921fc9cc7a9a7ff7e078d5e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
